# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/event/domain/localized_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*proto/event/domain/localized_message.proto\x12\x16\x62ucketeer.event.domain\"3\n\x10LocalizedMessage\x12\x0e\n\x06locale\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tB6Z4github.com/bucketeer-io/bucketeer/proto/event/domainb\x06proto3')



_LOCALIZEDMESSAGE = DESCRIPTOR.message_types_by_name['LocalizedMessage']
LocalizedMessage = _reflection.GeneratedProtocolMessageType('LocalizedMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCALIZEDMESSAGE,
  '__module__' : 'proto.event.domain.localized_message_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.event.domain.LocalizedMessage)
  })
_sym_db.RegisterMessage(LocalizedMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/bucketeer-io/bucketeer/proto/event/domain'
  _LOCALIZEDMESSAGE._serialized_start=70
  _LOCALIZEDMESSAGE._serialized_end=121
# @@protoc_insertion_point(module_scope)
