{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "api.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "api.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
        type: Utilization
  {{- if .Values.hpa.metrics.sseConnections.enabled }}
  - type: Pods
    pods:
      metric:
        name: {{ required "hpa.metrics.sseConnections.metricName is required" .Values.hpa.metrics.sseConnections.metricName }}
      target:
        type: AverageValue
        averageValue: "{{ required "hpa.metrics.sseConnections.targetAverageValue is required" .Values.hpa.metrics.sseConnections.targetAverageValue }}"
  {{- end }}
{{ end }}
