// Copyright 2024 The Bucketeer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: proto/feature/flag_trigger.proto

package feature

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagTrigger_Type int32

const (
	FlagTrigger_Type_UNKNOWN FlagTrigger_Type = 0
	FlagTrigger_Type_WEBHOOK FlagTrigger_Type = 1
)

// Enum value maps for FlagTrigger_Type.
var (
	FlagTrigger_Type_name = map[int32]string{
		0: "Type_UNKNOWN",
		1: "Type_WEBHOOK",
	}
	FlagTrigger_Type_value = map[string]int32{
		"Type_UNKNOWN": 0,
		"Type_WEBHOOK": 1,
	}
)

func (x FlagTrigger_Type) Enum() *FlagTrigger_Type {
	p := new(FlagTrigger_Type)
	*p = x
	return p
}

func (x FlagTrigger_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagTrigger_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_feature_flag_trigger_proto_enumTypes[0].Descriptor()
}

func (FlagTrigger_Type) Type() protoreflect.EnumType {
	return &file_proto_feature_flag_trigger_proto_enumTypes[0]
}

func (x FlagTrigger_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagTrigger_Type.Descriptor instead.
func (FlagTrigger_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_feature_flag_trigger_proto_rawDescGZIP(), []int{0, 0}
}

type FlagTrigger_Action int32

const (
	FlagTrigger_Action_UNKNOWN FlagTrigger_Action = 0
	FlagTrigger_Action_ON      FlagTrigger_Action = 1
	FlagTrigger_Action_OFF     FlagTrigger_Action = 2
)

// Enum value maps for FlagTrigger_Action.
var (
	FlagTrigger_Action_name = map[int32]string{
		0: "Action_UNKNOWN",
		1: "Action_ON",
		2: "Action_OFF",
	}
	FlagTrigger_Action_value = map[string]int32{
		"Action_UNKNOWN": 0,
		"Action_ON":      1,
		"Action_OFF":     2,
	}
)

func (x FlagTrigger_Action) Enum() *FlagTrigger_Action {
	p := new(FlagTrigger_Action)
	*p = x
	return p
}

func (x FlagTrigger_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagTrigger_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_feature_flag_trigger_proto_enumTypes[1].Descriptor()
}

func (FlagTrigger_Action) Type() protoreflect.EnumType {
	return &file_proto_feature_flag_trigger_proto_enumTypes[1]
}

func (x FlagTrigger_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagTrigger_Action.Descriptor instead.
func (FlagTrigger_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_feature_flag_trigger_proto_rawDescGZIP(), []int{0, 1}
}

type FlagTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	FeatureId            string             `protobuf:"bytes,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id"`
	EnvironmentNamespace string             `protobuf:"bytes,3,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace"`
	Type                 FlagTrigger_Type   `protobuf:"varint,4,opt,name=type,proto3,enum=bucketeer.feature.FlagTrigger_Type" json:"type"`
	Action               FlagTrigger_Action `protobuf:"varint,5,opt,name=action,proto3,enum=bucketeer.feature.FlagTrigger_Action" json:"action"`
	Description          string             `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	TriggerCount         int32              `protobuf:"varint,7,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count"`
	LastTriggeredAt      int64              `protobuf:"varint,8,opt,name=last_triggered_at,json=lastTriggeredAt,proto3" json:"last_triggered_at"`
	Token                string             `protobuf:"bytes,9,opt,name=token,proto3" json:"token"`
	Disabled             bool               `protobuf:"varint,10,opt,name=disabled,proto3" json:"disabled"`
	CreatedAt            int64              `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            int64              `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *FlagTrigger) Reset() {
	*x = FlagTrigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feature_flag_trigger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagTrigger) ProtoMessage() {}

func (x *FlagTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feature_flag_trigger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagTrigger.ProtoReflect.Descriptor instead.
func (*FlagTrigger) Descriptor() ([]byte, []int) {
	return file_proto_feature_flag_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *FlagTrigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlagTrigger) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *FlagTrigger) GetEnvironmentNamespace() string {
	if x != nil {
		return x.EnvironmentNamespace
	}
	return ""
}

func (x *FlagTrigger) GetType() FlagTrigger_Type {
	if x != nil {
		return x.Type
	}
	return FlagTrigger_Type_UNKNOWN
}

func (x *FlagTrigger) GetAction() FlagTrigger_Action {
	if x != nil {
		return x.Action
	}
	return FlagTrigger_Action_UNKNOWN
}

func (x *FlagTrigger) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlagTrigger) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

func (x *FlagTrigger) GetLastTriggeredAt() int64 {
	if x != nil {
		return x.LastTriggeredAt
	}
	return 0
}

func (x *FlagTrigger) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FlagTrigger) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *FlagTrigger) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FlagTrigger) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_proto_feature_flag_trigger_proto protoreflect.FileDescriptor

var file_proto_feature_flag_trigger_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x66, 0x6c, 0x61, 0x67, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xb5, 0x04, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x15, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x14, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x65, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x25, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x54, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x2a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x45, 0x42, 0x48, 0x4f, 0x4f, 0x4b, 0x10, 0x01,
	0x22, 0x3b, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x02, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x65, 0x65, 0x72, 0x2d, 0x69, 0x6f, 0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_feature_flag_trigger_proto_rawDescOnce sync.Once
	file_proto_feature_flag_trigger_proto_rawDescData = file_proto_feature_flag_trigger_proto_rawDesc
)

func file_proto_feature_flag_trigger_proto_rawDescGZIP() []byte {
	file_proto_feature_flag_trigger_proto_rawDescOnce.Do(func() {
		file_proto_feature_flag_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_feature_flag_trigger_proto_rawDescData)
	})
	return file_proto_feature_flag_trigger_proto_rawDescData
}

var file_proto_feature_flag_trigger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_feature_flag_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_feature_flag_trigger_proto_goTypes = []interface{}{
	(FlagTrigger_Type)(0),   // 0: bucketeer.feature.FlagTrigger.Type
	(FlagTrigger_Action)(0), // 1: bucketeer.feature.FlagTrigger.Action
	(*FlagTrigger)(nil),     // 2: bucketeer.feature.FlagTrigger
}
var file_proto_feature_flag_trigger_proto_depIdxs = []int32{
	0, // 0: bucketeer.feature.FlagTrigger.type:type_name -> bucketeer.feature.FlagTrigger.Type
	1, // 1: bucketeer.feature.FlagTrigger.action:type_name -> bucketeer.feature.FlagTrigger.Action
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_feature_flag_trigger_proto_init() }
func file_proto_feature_flag_trigger_proto_init() {
	if File_proto_feature_flag_trigger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_feature_flag_trigger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagTrigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_feature_flag_trigger_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_feature_flag_trigger_proto_goTypes,
		DependencyIndexes: file_proto_feature_flag_trigger_proto_depIdxs,
		EnumInfos:         file_proto_feature_flag_trigger_proto_enumTypes,
		MessageInfos:      file_proto_feature_flag_trigger_proto_msgTypes,
	}.Build()
	File_proto_feature_flag_trigger_proto = out.File
	file_proto_feature_flag_trigger_proto_rawDesc = nil
	file_proto_feature_flag_trigger_proto_goTypes = nil
	file_proto_feature_flag_trigger_proto_depIdxs = nil
}
