kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "datadog"
spec:
  global:
    clusterName: "your-cluster-name-here"
    site: "ap1.datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    tags:
      - "env:local"
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
