// Copyright 2022 The Bucketeer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: proto/autoops/command.proto

package autoops

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAutoOpsRuleCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeatureId           string                `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	OpsType             OpsType               `protobuf:"varint,2,opt,name=ops_type,json=opsType,proto3,enum=bucketeer.autoops.OpsType" json:"ops_type,omitempty"`
	OpsEventRateClauses []*OpsEventRateClause `protobuf:"bytes,3,rep,name=ops_event_rate_clauses,json=opsEventRateClauses,proto3" json:"ops_event_rate_clauses,omitempty"`
	DatetimeClauses     []*DatetimeClause     `protobuf:"bytes,4,rep,name=datetime_clauses,json=datetimeClauses,proto3" json:"datetime_clauses,omitempty"`
	WebhookClauses      []*WebhookClause      `protobuf:"bytes,5,rep,name=webhook_clauses,json=webhookClauses,proto3" json:"webhook_clauses,omitempty"`
}

func (x *CreateAutoOpsRuleCommand) Reset() {
	*x = CreateAutoOpsRuleCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAutoOpsRuleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAutoOpsRuleCommand) ProtoMessage() {}

func (x *CreateAutoOpsRuleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAutoOpsRuleCommand.ProtoReflect.Descriptor instead.
func (*CreateAutoOpsRuleCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAutoOpsRuleCommand) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *CreateAutoOpsRuleCommand) GetOpsType() OpsType {
	if x != nil {
		return x.OpsType
	}
	return OpsType_ENABLE_FEATURE
}

func (x *CreateAutoOpsRuleCommand) GetOpsEventRateClauses() []*OpsEventRateClause {
	if x != nil {
		return x.OpsEventRateClauses
	}
	return nil
}

func (x *CreateAutoOpsRuleCommand) GetDatetimeClauses() []*DatetimeClause {
	if x != nil {
		return x.DatetimeClauses
	}
	return nil
}

func (x *CreateAutoOpsRuleCommand) GetWebhookClauses() []*WebhookClause {
	if x != nil {
		return x.WebhookClauses
	}
	return nil
}

type ChangeAutoOpsRuleOpsTypeCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpsType OpsType `protobuf:"varint,1,opt,name=ops_type,json=opsType,proto3,enum=bucketeer.autoops.OpsType" json:"ops_type,omitempty"`
}

func (x *ChangeAutoOpsRuleOpsTypeCommand) Reset() {
	*x = ChangeAutoOpsRuleOpsTypeCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeAutoOpsRuleOpsTypeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAutoOpsRuleOpsTypeCommand) ProtoMessage() {}

func (x *ChangeAutoOpsRuleOpsTypeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAutoOpsRuleOpsTypeCommand.ProtoReflect.Descriptor instead.
func (*ChangeAutoOpsRuleOpsTypeCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeAutoOpsRuleOpsTypeCommand) GetOpsType() OpsType {
	if x != nil {
		return x.OpsType
	}
	return OpsType_ENABLE_FEATURE
}

type DeleteAutoOpsRuleCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAutoOpsRuleCommand) Reset() {
	*x = DeleteAutoOpsRuleCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAutoOpsRuleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAutoOpsRuleCommand) ProtoMessage() {}

func (x *DeleteAutoOpsRuleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAutoOpsRuleCommand.ProtoReflect.Descriptor instead.
func (*DeleteAutoOpsRuleCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{2}
}

type ChangeAutoOpsRuleTriggeredAtCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeAutoOpsRuleTriggeredAtCommand) Reset() {
	*x = ChangeAutoOpsRuleTriggeredAtCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeAutoOpsRuleTriggeredAtCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAutoOpsRuleTriggeredAtCommand) ProtoMessage() {}

func (x *ChangeAutoOpsRuleTriggeredAtCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAutoOpsRuleTriggeredAtCommand.ProtoReflect.Descriptor instead.
func (*ChangeAutoOpsRuleTriggeredAtCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{3}
}

type AddOpsEventRateClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpsEventRateClause *OpsEventRateClause `protobuf:"bytes,1,opt,name=ops_event_rate_clause,json=opsEventRateClause,proto3" json:"ops_event_rate_clause,omitempty"`
}

func (x *AddOpsEventRateClauseCommand) Reset() {
	*x = AddOpsEventRateClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOpsEventRateClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOpsEventRateClauseCommand) ProtoMessage() {}

func (x *AddOpsEventRateClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOpsEventRateClauseCommand.ProtoReflect.Descriptor instead.
func (*AddOpsEventRateClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{4}
}

func (x *AddOpsEventRateClauseCommand) GetOpsEventRateClause() *OpsEventRateClause {
	if x != nil {
		return x.OpsEventRateClause
	}
	return nil
}

type ChangeOpsEventRateClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OpsEventRateClause *OpsEventRateClause `protobuf:"bytes,2,opt,name=ops_event_rate_clause,json=opsEventRateClause,proto3" json:"ops_event_rate_clause,omitempty"`
}

func (x *ChangeOpsEventRateClauseCommand) Reset() {
	*x = ChangeOpsEventRateClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeOpsEventRateClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOpsEventRateClauseCommand) ProtoMessage() {}

func (x *ChangeOpsEventRateClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOpsEventRateClauseCommand.ProtoReflect.Descriptor instead.
func (*ChangeOpsEventRateClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeOpsEventRateClauseCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeOpsEventRateClauseCommand) GetOpsEventRateClause() *OpsEventRateClause {
	if x != nil {
		return x.OpsEventRateClause
	}
	return nil
}

type DeleteClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteClauseCommand) Reset() {
	*x = DeleteClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClauseCommand) ProtoMessage() {}

func (x *DeleteClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClauseCommand.ProtoReflect.Descriptor instead.
func (*DeleteClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClauseCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddDatetimeClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatetimeClause *DatetimeClause `protobuf:"bytes,1,opt,name=datetime_clause,json=datetimeClause,proto3" json:"datetime_clause,omitempty"`
}

func (x *AddDatetimeClauseCommand) Reset() {
	*x = AddDatetimeClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDatetimeClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDatetimeClauseCommand) ProtoMessage() {}

func (x *AddDatetimeClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDatetimeClauseCommand.ProtoReflect.Descriptor instead.
func (*AddDatetimeClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{7}
}

func (x *AddDatetimeClauseCommand) GetDatetimeClause() *DatetimeClause {
	if x != nil {
		return x.DatetimeClause
	}
	return nil
}

type ChangeDatetimeClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DatetimeClause *DatetimeClause `protobuf:"bytes,2,opt,name=datetime_clause,json=datetimeClause,proto3" json:"datetime_clause,omitempty"`
}

func (x *ChangeDatetimeClauseCommand) Reset() {
	*x = ChangeDatetimeClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDatetimeClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDatetimeClauseCommand) ProtoMessage() {}

func (x *ChangeDatetimeClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDatetimeClauseCommand.ProtoReflect.Descriptor instead.
func (*ChangeDatetimeClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeDatetimeClauseCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeDatetimeClauseCommand) GetDatetimeClause() *DatetimeClause {
	if x != nil {
		return x.DatetimeClause
	}
	return nil
}

type CreateWebhookCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateWebhookCommand) Reset() {
	*x = CreateWebhookCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWebhookCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookCommand) ProtoMessage() {}

func (x *CreateWebhookCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookCommand.ProtoReflect.Descriptor instead.
func (*CreateWebhookCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{9}
}

func (x *CreateWebhookCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWebhookCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ChangeWebhookNameCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeWebhookNameCommand) Reset() {
	*x = ChangeWebhookNameCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeWebhookNameCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeWebhookNameCommand) ProtoMessage() {}

func (x *ChangeWebhookNameCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeWebhookNameCommand.ProtoReflect.Descriptor instead.
func (*ChangeWebhookNameCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeWebhookNameCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeWebhookDescriptionCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ChangeWebhookDescriptionCommand) Reset() {
	*x = ChangeWebhookDescriptionCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeWebhookDescriptionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeWebhookDescriptionCommand) ProtoMessage() {}

func (x *ChangeWebhookDescriptionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeWebhookDescriptionCommand.ProtoReflect.Descriptor instead.
func (*ChangeWebhookDescriptionCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeWebhookDescriptionCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteWebhookCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWebhookCommand) Reset() {
	*x = DeleteWebhookCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWebhookCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookCommand) ProtoMessage() {}

func (x *DeleteWebhookCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookCommand.ProtoReflect.Descriptor instead.
func (*DeleteWebhookCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{12}
}

type AddWebhookClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WebhookClause *WebhookClause `protobuf:"bytes,1,opt,name=webhook_clause,json=webhookClause,proto3" json:"webhook_clause,omitempty"`
}

func (x *AddWebhookClauseCommand) Reset() {
	*x = AddWebhookClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWebhookClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWebhookClauseCommand) ProtoMessage() {}

func (x *AddWebhookClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWebhookClauseCommand.ProtoReflect.Descriptor instead.
func (*AddWebhookClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{13}
}

func (x *AddWebhookClauseCommand) GetWebhookClause() *WebhookClause {
	if x != nil {
		return x.WebhookClause
	}
	return nil
}

type ChangeWebhookClauseCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WebhookClause *WebhookClause `protobuf:"bytes,2,opt,name=webhook_clause,json=webhookClause,proto3" json:"webhook_clause,omitempty"`
}

func (x *ChangeWebhookClauseCommand) Reset() {
	*x = ChangeWebhookClauseCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_autoops_command_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeWebhookClauseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeWebhookClauseCommand) ProtoMessage() {}

func (x *ChangeWebhookClauseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_autoops_command_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeWebhookClauseCommand.ProtoReflect.Descriptor instead.
func (*ChangeWebhookClauseCommand) Descriptor() ([]byte, []int) {
	return file_proto_autoops_command_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeWebhookClauseCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeWebhookClauseCommand) GetWebhookClause() *WebhookClause {
	if x != nil {
		return x.WebhookClause
	}
	return nil
}

var File_proto_autoops_command_proto protoreflect.FileDescriptor

var file_proto_autoops_command_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73,
	0x1a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2f,
	0x61, 0x75, 0x74, 0x6f, 0x5f, 0x6f, 0x70, 0x73, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6f,
	0x70, 0x73, 0x2f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe5, 0x02, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x4f, 0x70,
	0x73, 0x52, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6f,
	0x70, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70,
	0x73, 0x2e, 0x4f, 0x70, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x5a, 0x0a, 0x16, 0x6f, 0x70, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x61,
	0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x4f, 0x70, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x13, 0x6f, 0x70, 0x73, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x12, 0x4c,
	0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0f, 0x64, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x0f,
	0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65,
	0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0e, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x1f, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x41, 0x75, 0x74, 0x6f, 0x4f, 0x70, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x4f, 0x70, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6f, 0x70,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73,
	0x2e, 0x4f, 0x70, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x4f,
	0x70, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x25, 0x0a,
	0x23, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x4f, 0x70, 0x73, 0x52, 0x75,
	0x6c, 0x65, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x41, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x22, 0x78, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x73, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x58, 0x0a, 0x15, 0x6f, 0x70, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e,
	0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x4f, 0x70, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x12, 0x6f, 0x70, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x22, 0x8b,
	0x01, 0x0a, 0x1f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x73, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x58, 0x0a, 0x15, 0x6f, 0x70, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75,
	0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x4f, 0x70, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x12, 0x6f, 0x70, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x4a, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x75,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0e, 0x64, 0x61, 0x74,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x22, 0x79, 0x0a, 0x1b, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x61,
	0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4a, 0x0a, 0x0f, 0x64, 0x61,
	0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e,
	0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x1f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x57, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x22, 0x62, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43,
	0x6c, 0x61, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x47, 0x0a, 0x0e,
	0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72,
	0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0d, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43,
	0x6c, 0x61, 0x75, 0x73, 0x65, 0x22, 0x75, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x57,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x47, 0x0a, 0x0e, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x63,
	0x6c, 0x61, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x65, 0x65, 0x72, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x2e,
	0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x0d, 0x77,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x65, 0x65, 0x72, 0x2d, 0x69, 0x6f, 0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x65, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6f, 0x70, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_autoops_command_proto_rawDescOnce sync.Once
	file_proto_autoops_command_proto_rawDescData = file_proto_autoops_command_proto_rawDesc
)

func file_proto_autoops_command_proto_rawDescGZIP() []byte {
	file_proto_autoops_command_proto_rawDescOnce.Do(func() {
		file_proto_autoops_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_autoops_command_proto_rawDescData)
	})
	return file_proto_autoops_command_proto_rawDescData
}

var file_proto_autoops_command_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_autoops_command_proto_goTypes = []interface{}{
	(*CreateAutoOpsRuleCommand)(nil),            // 0: bucketeer.autoops.CreateAutoOpsRuleCommand
	(*ChangeAutoOpsRuleOpsTypeCommand)(nil),     // 1: bucketeer.autoops.ChangeAutoOpsRuleOpsTypeCommand
	(*DeleteAutoOpsRuleCommand)(nil),            // 2: bucketeer.autoops.DeleteAutoOpsRuleCommand
	(*ChangeAutoOpsRuleTriggeredAtCommand)(nil), // 3: bucketeer.autoops.ChangeAutoOpsRuleTriggeredAtCommand
	(*AddOpsEventRateClauseCommand)(nil),        // 4: bucketeer.autoops.AddOpsEventRateClauseCommand
	(*ChangeOpsEventRateClauseCommand)(nil),     // 5: bucketeer.autoops.ChangeOpsEventRateClauseCommand
	(*DeleteClauseCommand)(nil),                 // 6: bucketeer.autoops.DeleteClauseCommand
	(*AddDatetimeClauseCommand)(nil),            // 7: bucketeer.autoops.AddDatetimeClauseCommand
	(*ChangeDatetimeClauseCommand)(nil),         // 8: bucketeer.autoops.ChangeDatetimeClauseCommand
	(*CreateWebhookCommand)(nil),                // 9: bucketeer.autoops.CreateWebhookCommand
	(*ChangeWebhookNameCommand)(nil),            // 10: bucketeer.autoops.ChangeWebhookNameCommand
	(*ChangeWebhookDescriptionCommand)(nil),     // 11: bucketeer.autoops.ChangeWebhookDescriptionCommand
	(*DeleteWebhookCommand)(nil),                // 12: bucketeer.autoops.DeleteWebhookCommand
	(*AddWebhookClauseCommand)(nil),             // 13: bucketeer.autoops.AddWebhookClauseCommand
	(*ChangeWebhookClauseCommand)(nil),          // 14: bucketeer.autoops.ChangeWebhookClauseCommand
	(OpsType)(0),                                // 15: bucketeer.autoops.OpsType
	(*OpsEventRateClause)(nil),                  // 16: bucketeer.autoops.OpsEventRateClause
	(*DatetimeClause)(nil),                      // 17: bucketeer.autoops.DatetimeClause
	(*WebhookClause)(nil),                       // 18: bucketeer.autoops.WebhookClause
}
var file_proto_autoops_command_proto_depIdxs = []int32{
	15, // 0: bucketeer.autoops.CreateAutoOpsRuleCommand.ops_type:type_name -> bucketeer.autoops.OpsType
	16, // 1: bucketeer.autoops.CreateAutoOpsRuleCommand.ops_event_rate_clauses:type_name -> bucketeer.autoops.OpsEventRateClause
	17, // 2: bucketeer.autoops.CreateAutoOpsRuleCommand.datetime_clauses:type_name -> bucketeer.autoops.DatetimeClause
	18, // 3: bucketeer.autoops.CreateAutoOpsRuleCommand.webhook_clauses:type_name -> bucketeer.autoops.WebhookClause
	15, // 4: bucketeer.autoops.ChangeAutoOpsRuleOpsTypeCommand.ops_type:type_name -> bucketeer.autoops.OpsType
	16, // 5: bucketeer.autoops.AddOpsEventRateClauseCommand.ops_event_rate_clause:type_name -> bucketeer.autoops.OpsEventRateClause
	16, // 6: bucketeer.autoops.ChangeOpsEventRateClauseCommand.ops_event_rate_clause:type_name -> bucketeer.autoops.OpsEventRateClause
	17, // 7: bucketeer.autoops.AddDatetimeClauseCommand.datetime_clause:type_name -> bucketeer.autoops.DatetimeClause
	17, // 8: bucketeer.autoops.ChangeDatetimeClauseCommand.datetime_clause:type_name -> bucketeer.autoops.DatetimeClause
	18, // 9: bucketeer.autoops.AddWebhookClauseCommand.webhook_clause:type_name -> bucketeer.autoops.WebhookClause
	18, // 10: bucketeer.autoops.ChangeWebhookClauseCommand.webhook_clause:type_name -> bucketeer.autoops.WebhookClause
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_autoops_command_proto_init() }
func file_proto_autoops_command_proto_init() {
	if File_proto_autoops_command_proto != nil {
		return
	}
	file_proto_autoops_auto_ops_rule_proto_init()
	file_proto_autoops_clause_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_autoops_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAutoOpsRuleCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeAutoOpsRuleOpsTypeCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAutoOpsRuleCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeAutoOpsRuleTriggeredAtCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOpsEventRateClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeOpsEventRateClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDatetimeClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDatetimeClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWebhookCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeWebhookNameCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeWebhookDescriptionCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWebhookCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWebhookClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_autoops_command_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeWebhookClauseCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_autoops_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_autoops_command_proto_goTypes,
		DependencyIndexes: file_proto_autoops_command_proto_depIdxs,
		MessageInfos:      file_proto_autoops_command_proto_msgTypes,
	}.Build()
	File_proto_autoops_command_proto = out.File
	file_proto_autoops_command_proto_rawDesc = nil
	file_proto_autoops_command_proto_goTypes = nil
	file_proto_autoops_command_proto_depIdxs = nil
}
