# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/environment/command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/environment/command.proto\x12\x15\x62ucketeer.environment\"x\n\x18\x43reateEnvironmentCommand\x12\x15\n\tnamespace\x18\x01 \x01(\tB\x02\x18\x01\x12\x10\n\x04name\x18\x02 \x01(\tB\x02\x18\x01\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\x12\x12\n\nproject_id\x18\x05 \x01(\t\"(\n\x18RenameEnvironmentCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\":\n#ChangeDescriptionEnvironmentCommand\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x1a\n\x18\x44\x65leteEnvironmentCommand\"7\n\x14\x43reateProjectCommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"6\n\x19\x43reateTrialProjectCommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"6\n\x1f\x43hangeDescriptionProjectCommand\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x16\n\x14\x45nableProjectCommand\"\x17\n\x15\x44isableProjectCommand\"\x1c\n\x1a\x43onvertTrialProjectCommandB5Z3github.com/bucketeer-io/bucketeer/proto/environmentb\x06proto3')



_CREATEENVIRONMENTCOMMAND = DESCRIPTOR.message_types_by_name['CreateEnvironmentCommand']
_RENAMEENVIRONMENTCOMMAND = DESCRIPTOR.message_types_by_name['RenameEnvironmentCommand']
_CHANGEDESCRIPTIONENVIRONMENTCOMMAND = DESCRIPTOR.message_types_by_name['ChangeDescriptionEnvironmentCommand']
_DELETEENVIRONMENTCOMMAND = DESCRIPTOR.message_types_by_name['DeleteEnvironmentCommand']
_CREATEPROJECTCOMMAND = DESCRIPTOR.message_types_by_name['CreateProjectCommand']
_CREATETRIALPROJECTCOMMAND = DESCRIPTOR.message_types_by_name['CreateTrialProjectCommand']
_CHANGEDESCRIPTIONPROJECTCOMMAND = DESCRIPTOR.message_types_by_name['ChangeDescriptionProjectCommand']
_ENABLEPROJECTCOMMAND = DESCRIPTOR.message_types_by_name['EnableProjectCommand']
_DISABLEPROJECTCOMMAND = DESCRIPTOR.message_types_by_name['DisableProjectCommand']
_CONVERTTRIALPROJECTCOMMAND = DESCRIPTOR.message_types_by_name['ConvertTrialProjectCommand']
CreateEnvironmentCommand = _reflection.GeneratedProtocolMessageType('CreateEnvironmentCommand', (_message.Message,), {
  'DESCRIPTOR' : _CREATEENVIRONMENTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.CreateEnvironmentCommand)
  })
_sym_db.RegisterMessage(CreateEnvironmentCommand)

RenameEnvironmentCommand = _reflection.GeneratedProtocolMessageType('RenameEnvironmentCommand', (_message.Message,), {
  'DESCRIPTOR' : _RENAMEENVIRONMENTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.RenameEnvironmentCommand)
  })
_sym_db.RegisterMessage(RenameEnvironmentCommand)

ChangeDescriptionEnvironmentCommand = _reflection.GeneratedProtocolMessageType('ChangeDescriptionEnvironmentCommand', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEDESCRIPTIONENVIRONMENTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.ChangeDescriptionEnvironmentCommand)
  })
_sym_db.RegisterMessage(ChangeDescriptionEnvironmentCommand)

DeleteEnvironmentCommand = _reflection.GeneratedProtocolMessageType('DeleteEnvironmentCommand', (_message.Message,), {
  'DESCRIPTOR' : _DELETEENVIRONMENTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.DeleteEnvironmentCommand)
  })
_sym_db.RegisterMessage(DeleteEnvironmentCommand)

CreateProjectCommand = _reflection.GeneratedProtocolMessageType('CreateProjectCommand', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPROJECTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.CreateProjectCommand)
  })
_sym_db.RegisterMessage(CreateProjectCommand)

CreateTrialProjectCommand = _reflection.GeneratedProtocolMessageType('CreateTrialProjectCommand', (_message.Message,), {
  'DESCRIPTOR' : _CREATETRIALPROJECTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.CreateTrialProjectCommand)
  })
_sym_db.RegisterMessage(CreateTrialProjectCommand)

ChangeDescriptionProjectCommand = _reflection.GeneratedProtocolMessageType('ChangeDescriptionProjectCommand', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEDESCRIPTIONPROJECTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.ChangeDescriptionProjectCommand)
  })
_sym_db.RegisterMessage(ChangeDescriptionProjectCommand)

EnableProjectCommand = _reflection.GeneratedProtocolMessageType('EnableProjectCommand', (_message.Message,), {
  'DESCRIPTOR' : _ENABLEPROJECTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.EnableProjectCommand)
  })
_sym_db.RegisterMessage(EnableProjectCommand)

DisableProjectCommand = _reflection.GeneratedProtocolMessageType('DisableProjectCommand', (_message.Message,), {
  'DESCRIPTOR' : _DISABLEPROJECTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.DisableProjectCommand)
  })
_sym_db.RegisterMessage(DisableProjectCommand)

ConvertTrialProjectCommand = _reflection.GeneratedProtocolMessageType('ConvertTrialProjectCommand', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTTRIALPROJECTCOMMAND,
  '__module__' : 'proto.environment.command_pb2'
  # @@protoc_insertion_point(class_scope:bucketeer.environment.ConvertTrialProjectCommand)
  })
_sym_db.RegisterMessage(ConvertTrialProjectCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/bucketeer-io/bucketeer/proto/environment'
  _CREATEENVIRONMENTCOMMAND.fields_by_name['namespace']._options = None
  _CREATEENVIRONMENTCOMMAND.fields_by_name['namespace']._serialized_options = b'\030\001'
  _CREATEENVIRONMENTCOMMAND.fields_by_name['name']._options = None
  _CREATEENVIRONMENTCOMMAND.fields_by_name['name']._serialized_options = b'\030\001'
  _CREATEENVIRONMENTCOMMAND._serialized_start=58
  _CREATEENVIRONMENTCOMMAND._serialized_end=178
  _RENAMEENVIRONMENTCOMMAND._serialized_start=180
  _RENAMEENVIRONMENTCOMMAND._serialized_end=220
  _CHANGEDESCRIPTIONENVIRONMENTCOMMAND._serialized_start=222
  _CHANGEDESCRIPTIONENVIRONMENTCOMMAND._serialized_end=280
  _DELETEENVIRONMENTCOMMAND._serialized_start=282
  _DELETEENVIRONMENTCOMMAND._serialized_end=308
  _CREATEPROJECTCOMMAND._serialized_start=310
  _CREATEPROJECTCOMMAND._serialized_end=365
  _CREATETRIALPROJECTCOMMAND._serialized_start=367
  _CREATETRIALPROJECTCOMMAND._serialized_end=421
  _CHANGEDESCRIPTIONPROJECTCOMMAND._serialized_start=423
  _CHANGEDESCRIPTIONPROJECTCOMMAND._serialized_end=477
  _ENABLEPROJECTCOMMAND._serialized_start=479
  _ENABLEPROJECTCOMMAND._serialized_end=501
  _DISABLEPROJECTCOMMAND._serialized_start=503
  _DISABLEPROJECTCOMMAND._serialized_end=526
  _CONVERTTRIALPROJECTCOMMAND._serialized_start=528
  _CONVERTTRIALPROJECTCOMMAND._serialized_end=556
# @@protoc_insertion_point(module_scope)
