# Makefile for the dashboard UI

# Install dependencies
.PHONY: install
install:
	yarn install

# Run the development server
.PHONY: dev
dev:
	yarn start

# Run the production server
.PHONY: serve
serve:
	yarn serve

# Build for production
.PHONY: build
build:
	yarn build
