{{- if eq (include "subscriber.deploy" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "subscriber.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "subscriber.name" . }}
    chart: {{ template "subscriber.chart" . }}
    release: {{ template "subscriber.fullname" . }}
    heritage: {{ .Release.Service }}
    envoy: "true"
    metrics: "true"
spec:
  {{- if eq (.Values.service.clusterIP | toString) "None" }}
  {{- if ne .Values.service.type "ClusterIP" }}
  {{- fail "Invalid configuration: when service.clusterIP is 'None', service.type must be 'ClusterIP'" }}
  {{- end }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: metrics
      port: {{ .Values.env.metricsPort }}
      protocol: TCP
    - name: admin
      port: {{ .Values.envoy.adminPort }}
      protocol: TCP
  selector:
    app: {{ template "subscriber.name" . }}
    release: {{ template "subscriber.fullname" . }}
{{- end }}