// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/bucketeer-io/bucketeer/pkg/account/domain"
	mysql "github.com/bucketeer-io/bucketeer/pkg/storage/v2/mysql"
	account "github.com/bucketeer-io/bucketeer/proto/account"
)

// MockAccountStorage is a mock of AccountStorage interface.
type MockAccountStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAccountStorageMockRecorder
}

// MockAccountStorageMockRecorder is the mock recorder for MockAccountStorage.
type MockAccountStorageMockRecorder struct {
	mock *MockAccountStorage
}

// NewMockAccountStorage creates a new mock instance.
func NewMockAccountStorage(ctrl *gomock.Controller) *MockAccountStorage {
	mock := &MockAccountStorage{ctrl: ctrl}
	mock.recorder = &MockAccountStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountStorage) EXPECT() *MockAccountStorageMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockAccountStorage) CreateAPIKey(ctx context.Context, k *domain.APIKey, environmentNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, k, environmentNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockAccountStorageMockRecorder) CreateAPIKey(ctx, k, environmentNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockAccountStorage)(nil).CreateAPIKey), ctx, k, environmentNamespace)
}

// CreateAccount mocks base method.
func (m *MockAccountStorage) CreateAccount(ctx context.Context, a *domain.Account, environmentNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, a, environmentNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountStorageMockRecorder) CreateAccount(ctx, a, environmentNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountStorage)(nil).CreateAccount), ctx, a, environmentNamespace)
}

// CreateAccountV2 mocks base method.
func (m *MockAccountStorage) CreateAccountV2(ctx context.Context, a *domain.AccountV2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountV2", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccountV2 indicates an expected call of CreateAccountV2.
func (mr *MockAccountStorageMockRecorder) CreateAccountV2(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountV2", reflect.TypeOf((*MockAccountStorage)(nil).CreateAccountV2), ctx, a)
}

// CreateAdminAccount mocks base method.
func (m *MockAccountStorage) CreateAdminAccount(ctx context.Context, a *domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminAccount", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdminAccount indicates an expected call of CreateAdminAccount.
func (mr *MockAccountStorageMockRecorder) CreateAdminAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminAccount", reflect.TypeOf((*MockAccountStorage)(nil).CreateAdminAccount), ctx, a)
}

// DeleteAccountV2 mocks base method.
func (m *MockAccountStorage) DeleteAccountV2(ctx context.Context, a *domain.AccountV2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountV2", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountV2 indicates an expected call of DeleteAccountV2.
func (mr *MockAccountStorageMockRecorder) DeleteAccountV2(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountV2", reflect.TypeOf((*MockAccountStorage)(nil).DeleteAccountV2), ctx, a)
}

// GetAPIKey mocks base method.
func (m *MockAccountStorage) GetAPIKey(ctx context.Context, id, environmentNamespace string) (*domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey", ctx, id, environmentNamespace)
	ret0, _ := ret[0].(*domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockAccountStorageMockRecorder) GetAPIKey(ctx, id, environmentNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockAccountStorage)(nil).GetAPIKey), ctx, id, environmentNamespace)
}

// GetAccount mocks base method.
func (m *MockAccountStorage) GetAccount(ctx context.Context, id, environmentNamespace string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id, environmentNamespace)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAccountStorageMockRecorder) GetAccount(ctx, id, environmentNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAccountStorage)(nil).GetAccount), ctx, id, environmentNamespace)
}

// GetAccountV2 mocks base method.
func (m *MockAccountStorage) GetAccountV2(ctx context.Context, email, organizationID string) (*domain.AccountV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountV2", ctx, email, organizationID)
	ret0, _ := ret[0].(*domain.AccountV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountV2 indicates an expected call of GetAccountV2.
func (mr *MockAccountStorageMockRecorder) GetAccountV2(ctx, email, organizationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountV2", reflect.TypeOf((*MockAccountStorage)(nil).GetAccountV2), ctx, email, organizationID)
}

// GetAccountV2ByEnvironmentID mocks base method.
func (m *MockAccountStorage) GetAccountV2ByEnvironmentID(ctx context.Context, email, environmentID string) (*domain.AccountV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountV2ByEnvironmentID", ctx, email, environmentID)
	ret0, _ := ret[0].(*domain.AccountV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountV2ByEnvironmentID indicates an expected call of GetAccountV2ByEnvironmentID.
func (mr *MockAccountStorageMockRecorder) GetAccountV2ByEnvironmentID(ctx, email, environmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountV2ByEnvironmentID", reflect.TypeOf((*MockAccountStorage)(nil).GetAccountV2ByEnvironmentID), ctx, email, environmentID)
}

// GetAccountsWithOrganization mocks base method.
func (m *MockAccountStorage) GetAccountsWithOrganization(ctx context.Context, email string) ([]*domain.AccountWithOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsWithOrganization", ctx, email)
	ret0, _ := ret[0].([]*domain.AccountWithOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsWithOrganization indicates an expected call of GetAccountsWithOrganization.
func (mr *MockAccountStorageMockRecorder) GetAccountsWithOrganization(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsWithOrganization", reflect.TypeOf((*MockAccountStorage)(nil).GetAccountsWithOrganization), ctx, email)
}

// GetAdminAccount mocks base method.
func (m *MockAccountStorage) GetAdminAccount(ctx context.Context, id string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminAccount", ctx, id)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminAccount indicates an expected call of GetAdminAccount.
func (mr *MockAccountStorageMockRecorder) GetAdminAccount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminAccount", reflect.TypeOf((*MockAccountStorage)(nil).GetAdminAccount), ctx, id)
}

// ListAPIKeys mocks base method.
func (m *MockAccountStorage) ListAPIKeys(ctx context.Context, whereParts []mysql.WherePart, orders []*mysql.Order, limit, offset int) ([]*account.APIKey, int, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIKeys", ctx, whereParts, orders, limit, offset)
	ret0, _ := ret[0].([]*account.APIKey)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListAPIKeys indicates an expected call of ListAPIKeys.
func (mr *MockAccountStorageMockRecorder) ListAPIKeys(ctx, whereParts, orders, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeys", reflect.TypeOf((*MockAccountStorage)(nil).ListAPIKeys), ctx, whereParts, orders, limit, offset)
}

// ListAccounts mocks base method.
func (m *MockAccountStorage) ListAccounts(ctx context.Context, whereParts []mysql.WherePart, orders []*mysql.Order, limit, offset int) ([]*account.Account, int, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, whereParts, orders, limit, offset)
	ret0, _ := ret[0].([]*account.Account)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockAccountStorageMockRecorder) ListAccounts(ctx, whereParts, orders, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockAccountStorage)(nil).ListAccounts), ctx, whereParts, orders, limit, offset)
}

// ListAccountsV2 mocks base method.
func (m *MockAccountStorage) ListAccountsV2(ctx context.Context, whereParts []mysql.WherePart, orders []*mysql.Order, limit, offset int) ([]*account.AccountV2, int, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsV2", ctx, whereParts, orders, limit, offset)
	ret0, _ := ret[0].([]*account.AccountV2)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListAccountsV2 indicates an expected call of ListAccountsV2.
func (mr *MockAccountStorageMockRecorder) ListAccountsV2(ctx, whereParts, orders, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsV2", reflect.TypeOf((*MockAccountStorage)(nil).ListAccountsV2), ctx, whereParts, orders, limit, offset)
}

// ListAdminAccounts mocks base method.
func (m *MockAccountStorage) ListAdminAccounts(ctx context.Context, whereParts []mysql.WherePart, orders []*mysql.Order, limit, offset int) ([]*account.Account, int, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminAccounts", ctx, whereParts, orders, limit, offset)
	ret0, _ := ret[0].([]*account.Account)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListAdminAccounts indicates an expected call of ListAdminAccounts.
func (mr *MockAccountStorageMockRecorder) ListAdminAccounts(ctx, whereParts, orders, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminAccounts", reflect.TypeOf((*MockAccountStorage)(nil).ListAdminAccounts), ctx, whereParts, orders, limit, offset)
}

// RunInTransaction mocks base method.
func (m *MockAccountStorage) RunInTransaction(ctx context.Context, f func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTransaction indicates an expected call of RunInTransaction.
func (mr *MockAccountStorageMockRecorder) RunInTransaction(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTransaction", reflect.TypeOf((*MockAccountStorage)(nil).RunInTransaction), ctx, f)
}

// UpdateAPIKey mocks base method.
func (m *MockAccountStorage) UpdateAPIKey(ctx context.Context, k *domain.APIKey, environmentNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAPIKey", ctx, k, environmentNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAPIKey indicates an expected call of UpdateAPIKey.
func (mr *MockAccountStorageMockRecorder) UpdateAPIKey(ctx, k, environmentNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAPIKey", reflect.TypeOf((*MockAccountStorage)(nil).UpdateAPIKey), ctx, k, environmentNamespace)
}

// UpdateAccount mocks base method.
func (m *MockAccountStorage) UpdateAccount(ctx context.Context, a *domain.Account, environmentNamespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, a, environmentNamespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockAccountStorageMockRecorder) UpdateAccount(ctx, a, environmentNamespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockAccountStorage)(nil).UpdateAccount), ctx, a, environmentNamespace)
}

// UpdateAccountV2 mocks base method.
func (m *MockAccountStorage) UpdateAccountV2(ctx context.Context, a *domain.AccountV2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountV2", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountV2 indicates an expected call of UpdateAccountV2.
func (mr *MockAccountStorageMockRecorder) UpdateAccountV2(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountV2", reflect.TypeOf((*MockAccountStorage)(nil).UpdateAccountV2), ctx, a)
}

// UpdateAdminAccount mocks base method.
func (m *MockAccountStorage) UpdateAdminAccount(ctx context.Context, a *domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminAccount", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminAccount indicates an expected call of UpdateAdminAccount.
func (mr *MockAccountStorageMockRecorder) UpdateAdminAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminAccount", reflect.TypeOf((*MockAccountStorage)(nil).UpdateAdminAccount), ctx, a)
}
