export const FEATURE_ID_MAX_LENGTH = 100;
export const FEATURE_NAME_MAX_LENGTH = 100;
export const FEATURE_TAG_MIN_SIZE = 1;
export const FEATURE_VARIATION_MIN_SIZE = 100;
export const FEATURE_DESCRIPTION_MAX_LENGTH = 100;
export const FEATURE_UPDATE_COMMENT_MAX_LENGTH = 100;

export const FEATURE_LIST_PAGE_SIZE = 50;
export const FEATURE_HISTORY_PAGE_SIZE = 10;
export const FEATURE_ACCOUNT_PAGE_SIZE = 1000;
