// Code generated by MockGen. DO NOT EDIT.
// Source: event_mysql.go
//
// Generated by this command:
//
//	mockgen -source=event_mysql.go -package=mock -destination=./mock/event_mysql.go
//

// Package mock is a generated GoMock package.
package mock
