name: pr-hadolint

on:
  pull_request:
    paths:
      - "**/Dockerfile*"
      - ".hadolint.yaml"

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Run Hadolint on all Dockerfiles
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          recursive: true
          failure-threshold: error
