name: pr-migration

on:
  pull_request:
    branches:
      - main
    paths:
      - "migration/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ATLAS_VERSION: v1.0.0

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Atlas
        uses: ariga/setup-atlas@2f3c785c89a15e1c0d07bcae3900fb5feb969eea # v0
        with:
          version: ${{ env.ATLAS_VERSION }}

      - name: Validate migration files
        run: make migration-validate
        
      - name: Check atlas.sum is up to date
        run: make migration-hash-check
