name: pr-trivy

on:
  pull_request:
    paths:
      - "**/go.mod"
      - "**/go.sum"
      - "**/yarn.lock"
      - "**/package-lock.json"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: fs # scan local filesystem (go.mod etc.), not docker images
          scanners: vuln # check for known CVEs only (not misconfig or secrets)
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
